"""initial schema

Revision ID: c2f59456c6fe
Revises: 
Create Date: 2026-04-19 18:29:50.256462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2f59456c6fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('chair_name', sa.String(length=100), nullable=True),
    sa.Column('agenda_1', sa.Text(), nullable=True),
    sa.Column('agenda_2', sa.Text(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('filled_seats', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('delegates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('student_id_cnic', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegates_committee_id'), 'delegates', ['committee_id'], unique=False)
    op.create_index(op.f('ix_delegates_email'), 'delegates', ['email'], unique=True)
    op.create_index(op.f('ix_delegates_roll_number'), 'delegates', ['roll_number'], unique=True)
    op.create_index(op.f('ix_delegates_student_id_cnic'), 'delegates', ['student_id_cnic'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delegates_student_id_cnic'), table_name='delegates')
    op.drop_index(op.f('ix_delegates_roll_number'), table_name='delegates')
    op.drop_index(op.f('ix_delegates_email'), table_name='delegates')
    op.drop_index(op.f('ix_delegates_committee_id'), table_name='delegates')
    op.drop_table('delegates')
    op.drop_table('committees')
    # ### end Alembic commands ###
