"""Add admin queries and system settings

Revision ID: c71afe97b8a7
Revises: c2f59456c6fe
Create Date: 2026-04-23 23:18:17.262032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c71afe97b8a7'
down_revision: Union[str, Sequence[str], None] = 'c2f59456c6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('admin_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('committee', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delegate_id'], ['delegates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_queries_delegate_id'), 'admin_queries', ['delegate_id'], unique=False)
    op.create_index(op.f('ix_admin_queries_id'), 'admin_queries', ['id'], unique=False)
    op.create_index(op.f('ix_admin_queries_roll_number'), 'admin_queries', ['roll_number'], unique=False)
    op.alter_column('delegates', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.create_foreign_key(None, 'delegates', 'committees', ['previous_committee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delegates', type_='foreignkey')
    op.alter_column('delegates', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_queries_roll_number'), table_name='admin_queries')
    op.drop_index(op.f('ix_admin_queries_id'), table_name='admin_queries')
    op.drop_index(op.f('ix_admin_queries_delegate_id'), table_name='admin_queries')
    op.drop_table('admin_queries')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
